version: "3.9"

services:
  db:
    image: postgres
    container_name: crypto-analytics-postgresql
    restart: always
    ports:
      - "1010:5432"
    volumes:
      - ~/crypto-analytics:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    image: crypto-analytics-backend
    container_name: crypto-analytics-backend
    restart: always
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "1020:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/crypto_analytics
      - SERVER_URL=0.0.0.0:8000
    depends_on:
      - db
  frontend:
    image: crypto-analytics-frontend
    container_name: crypto-analytics-frontend
    restart: always
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        - API_URL=http://localhost:1020
        - RELOAD_INTERVAL= 0
        - COINGECKO_API_KEY = ****UPDATE****
    ports:
      - "1030:80"
    depends_on:
      - backend
