INSERT INTO definitions (api_key, precision) VALUES ('bitcoin', 2);
INSERT INTO definitions (api_key, precision) VALUES ('ethereum', 2);
INSERT INTO definitions (api_key, precision) VALUES ('chainlink', 2);
INSERT INTO definitions (api_key, precision) VALUES ('litecoin', 2);
INSERT INTO definitions (api_key, precision) VALUES ('bitcoin-cash', 2);
INSERT INTO definitions (api_key, precision) VALUES ('blockstack', 2);
INSERT INTO definitions (api_key, precision) VALUES ('defichain', 2);
INSERT INTO definitions (api_key, precision) VALUES ('binancecoin', 2);
INSERT INTO definitions (api_key, precision) VALUES ('unit-protocol-duck', 4);